### PR TITLE
recreate base test project

### PR DESCRIPTION
**Pull request by jrushlow**
this replicates the state of the app created for one of the maker bundle tests cases where we get

```
1) Symfony\Bundle\MakerBundle\Tests\Maker\MakeAuthenticatorTest::testExecute with data set "auth_login_form_custom_username_field" (Symfony\Bundle\MakerBundle\Test\MakerTestDetails Object (...))
Exception: Error running command: "composer require security doctrine/annotations twig symfony/form". Output: "". Error: "Using version 1.13.x-dev for doctrine/annotations

....

Symfony operations: 4 recipes (6674f4cd0b8ee356f248b472279a84b7)
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/security-bundle (>=5.1): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (>=5.0): From github.com/symfony/recipes:master
  - Configuring twig/extra-bundle (>=3.x-dev): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In ClassLoader.php line 478:
!!                                                                             
!!    Class "Doctrine\Common\Cache\CacheProvider" not found while loading "".  
!!                                                                             
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```
This particular composer.lock was built on PHP `8.0` but failure occurs on `7.4` when using dev dependencies as well.

### CODE REVIEW

**Comment by jrushlow** [comment]
if I start with this base && then `composer install`, we are good. If I then try to `composer require doctrine/annotations` we get:
```
developer@6f43b67d8732:/var/htdocs$ composer require doctrine/annotations
Using version 1.13.x-dev for doctrine/annotations
./composer.json has been updated
Running composer update doctrine/annotations
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking doctrine/annotations (1.13.x-dev c66f06b)
  - Locking doctrine/lexer (1.3.x-dev 59bfb3b)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (1.3.x-dev 59bfb3b): Extracting archive
  - Installing doctrine/annotations (1.13.x-dev c66f06b): Extracting archive
Generating optimized autoload files
49 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In ClassLoader.php line 476:
!!                                                                             
!!    Class "Doctrine\Common\Cache\CacheProvider" not found while loading "".  
!!                                                                             
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

If you try to run `bin/console cache:clear` immediately after the above, we get the same error.

**Comment by Nyholm** [comment]
Are you on PHP8?

**Comment by Nyholm** [comment]
I've submitted a bugfix.

**Comment by jrushlow** [comment]
Awesome! and Thanks! Yes PHP 8 but the failure also occurred on PHP 7.4

**Pull request merged**
